Use ESM, and update rdf-ext
rdf-ext/rdf-utils-dataset pull request #3
Opened 2022-05-09 11:28 UTC by cristianvasquez

Hello @bergos, 

This pull request updates the rdf-ext lib and ports the code to ESM

I moved this one to ESM because it is a dependency of https://github.com/zazuko/trifid-handler-fetch, which is being ported to ESM using `"rdf-ext": "^2.0.1"`

2022-05-17 13:18 UTC, tpluscode commented on README.md
> +import { resource } from 'rdf-utils-dataset/resource.js'
This does not match the export. Should be default-imported or changed in `resource.js`

```suggestion
import resource from 'rdf-utils-dataset/resource.js'
```

2022-05-17 17:48 UTC, cristianvasquez commented
Thanks for the observation!

2022-05-23 07:27 UTC, bergos requested changes

2022-05-23 07:27 UTC, bergos commented on README.md
> +import resource from 'rdf-utils-dataset'
I think this should be:

```js
import { resource } from 'rdf-utils-dataset'
```

Everything else looks good.

2022-05-23 15:50 UTC, cristianvasquez commented
I've changed the documentation.

I don't have write access to merge...

2022-05-24 08:56 UTC, bergos approved these changes

2022-05-24 08:57 UTC, merged